version: '3.1'

volumes:  
  mqdata:

services:  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    labels:
      NAME: "rabbitmq"
    container_name: rabbitMQ
    volumes:
      - mqdata:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks:
      - rede
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: MagicWord
      RABBITMQ_DEFAULT_VHOST: TransactionMessage
      
  publisher:
    build: 
      context: ./Message.Publisher
      dockerfile: Dockerfile
    environment:
      QUEUECONFIG_HOSTNAME: rabbitmq
      QUEUECONFIG_PORT: 5672
      QUEUECONFIG_PASSWORD: MagicWord
      QUEUECONFIG_VIRTUALHOST: TransactionMessage
    networks:
      - rede
    depends_on:      
      - "rabbitmq"

  consumer-ted:
    build: 
      context: ./Message.Consumer
      dockerfile: Dockerfile
    environment:
      QUEUECONFIG_HOSTNAME: rabbitmq
      QUEUECONFIG_PORT: 5672
      QUEUECONFIG_PASSWORD: MagicWord
      QUEUECONFIG_VIRTUALHOST: TransactionMessage
      QUEUECONFIG_QUEUENAME: financial-transactions-ted
    networks:
      - rede
    depends_on:
      - "rabbitmq"
      - "publisher"

  consumer-doc:
    build: 
      context: ./Message.Consumer
      dockerfile: Dockerfile
    environment:
      QUEUECONFIG_HOSTNAME: rabbitmq
      QUEUECONFIG_PORT: 5672
      QUEUECONFIG_PASSWORD: MagicWord
      QUEUECONFIG_VIRTUALHOST: TransactionMessage
      QUEUECONFIG_QUEUENAME: financial-transactions-doc
    networks:
      - rede
    depends_on:
      - "rabbitmq"
      - "publisher"

  consumer-pix:
    build: 
      context: ./Message.Consumer
      dockerfile: Dockerfile
    environment:
      QUEUECONFIG_HOSTNAME: rabbitmq
      QUEUECONFIG_PORT: 5672
      QUEUECONFIG_PASSWORD: MagicWord
      QUEUECONFIG_VIRTUALHOST: TransactionMessage
      QUEUECONFIG_QUEUENAME: financial-transactions-pix
    networks:
      - rede
    depends_on:
      - "rabbitmq"
      - "publisher"

networks:
  rede:
    driver: bridge